import { StyleSheet, Dimensions } from 'react-native';
import { colors } from '../../../../utils/theme';

const { width } = Dimensions.get('window');

export const boardStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  gameArea: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    width: '100%',
  },
  board: {
    backgroundColor: colors.boardBackground,
    borderRadius: 12,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.shadowDark,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 8,
  },
  row: {
    flexDirection: 'row',
  },
  cell: {
    margin: 2,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.cellBorder,
    overflow: 'hidden',
  },
  cellContent: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 6,
  },
  cellText: {
    color: colors.textLight,
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
  },
  cellWithIcon: {
    backgroundColor: colors.cellWithIcon,
  },
  cellHighlighted: {
    backgroundColor: colors.cellHighlighted,
    borderColor: colors.cellBorder,
  },
  cellEmpty: {
    backgroundColor: colors.cellEmpty,
  },
  cellHint: {
    backgroundColor: 'rgba(255, 255, 100, 0.3)',
    borderColor: 'rgba(255, 255, 100, 0.7)',
  },
  cellRemoved: {
    opacity: 0,
  },
  levelCompleteOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  levelCompleteContainer: {
    backgroundColor: colors.successBackground,
    padding: 25,
    borderRadius: 16,
    alignItems: 'center',
    width: width * 0.8,
    maxWidth: 400,
    shadowColor: colors.shadowDark,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
    elevation: 10,
  },
  levelCompleteText: {
    color: colors.textLight,
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  levelCompleteScore: {
    color: colors.textLight,
    fontSize: 22,
    marginBottom: 15,
    textAlign: 'center',
  },
  nextLevelButton: {
    backgroundColor: colors.primaryButton,
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 8,
    marginTop: 15,
    shadowColor: colors.shadowDark,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  nextLevelButtonText: {
    color: colors.textLight,
    fontSize: 18,
    fontWeight: 'bold',
  },
  messageContainer: {
    position: 'absolute',
    padding: 15,
    backgroundColor: colors.messageBackground,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.shadowDark,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
    zIndex: 5,
  },
  messageText: {
    color: colors.textLight,
    fontSize: 18,
    fontWeight: '600',
  },
  gameOverContainer: {
    backgroundColor: colors.dangerBackground,
    padding: 25,
    borderRadius: 16,
    alignItems: 'center',
    width: width * 0.8,
    maxWidth: 400,
    shadowColor: colors.shadowDark,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
    elevation: 10,
  },
  gameOverText: {
    color: colors.textLight,
    fontSize: 28,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  gameOverScore: {
    color: colors.textLight,
    fontSize: 22,
    marginBottom: 15,
    textAlign: 'center',
  },
  restartButton: {
    backgroundColor: colors.primaryButton,
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 8,
    marginTop: 15,
    shadowColor: colors.shadowDark,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  restartButtonText: {
    color: colors.textLight,
    fontSize: 18,
    fontWeight: 'bold',
  },
}); 